---
abstract: "'Unbless' Perl objects."
author:
  - 'Ian Brayshaw <ibb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Exception: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-Damn
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.006'
resources:
  repository: git://github.com/denormal/perl-Acme-Damn.git
version: '0.08'
